//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBack
    {
        public int Feed_id { get; set; }
        public string giver_id { get; set; }
        public string reciever_id { get; set; }
        public int session_id { get; set; }
        public string comment { get; set; }
        public int Level_id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual Level Level { get; set; }
        public virtual session session { get; set; }
    }
}
