//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int payment_id { get; set; }
        public int subscription_id { get; set; }
        public System.DateTime payment_date { get; set; }
        public double amount { get; set; }
        public Nullable<int> payment_method_id { get; set; }
    
        public virtual payment_methods payment_methods { get; set; }
        public virtual subscription subscription { get; set; }
    }
}
