//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class session
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public session()
        {
            this.FeedBacks = new HashSet<FeedBack>();
            this.student_session_registrations = new HashSet<student_session_registrations>();
        }
    
        public int session_id { get; set; }
        public string speaker_id { get; set; }
        public string description { get; set; }
        public System.DateTime start_time { get; set; }
        public System.DateTime end_time { get; set; }
        public string Session_Link { get; set; }
        public string Session_List { get; set; }
        public int capacity { get; set; }
        public int remaining_capacity { get; set; }
        public bool is_cancelled { get; set; }
        public Nullable<int> minumum_Level { get; set; }
        public Nullable<int> maximum_Level { get; set; }
        public int session_language_id { get; set; }
        public Nullable<bool> is_free { get; set; }
        public Nullable<int> Category_id { get; set; }
        public string Name { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedBack> FeedBacks { get; set; }
        public virtual language language { get; set; }
        public virtual Level Level { get; set; }
        public virtual Level Level1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<student_session_registrations> student_session_registrations { get; set; }
    }
}
