//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_languages
    {
        public int User_language_id { get; set; }
        public string User_id { get; set; }
        public int language_id { get; set; }
        public int language_level { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual language language { get; set; }
        public virtual Level Level { get; set; }
    }
}
